feelings/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.views.generic import TemplateView
from users import urls as user_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name = 'home'),
    url(r'^users/', include((user_urls, 'users'), namespace='users')),
]

users/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^logout/$', views.LogoutView.as_view(),name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(),name='signup'),
    url('^', include('django.contrib.auth.urls')),

]

thoughts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

CONDITIONS = (
    (0, 'ecstatic'),
    (5, 'Passionate'),
    (10, 'Happy'),
    (15, 'optimistic'),
    (20, 'content'),
    (25, 'Bored'),
    (26, 'tired'),
    (27, 'hungry'),
    (30, 'pessimistic'),
    (35, 'Frustrated'),
    (40, 'Overwhelmed'),
    (45, 'Disappointed'),
    (50, 'Worried'),
    (55, 'Angry'),
    (60, 'Jealous'),
    (65, 'Insecure'),
    (70, 'Guilty'),
    (75, 'fear'),
    (80, 'Grief'),
    (85, 'Despair'),
    (90, 'Paranoid')
)

class Thought(models.Model):
    user = models.ForeignKey(User, related_name='thoughts', on_delete=models.CASCADE)
    recorded_at = models.DateTimeField(default=timezone.now, editable=False)
    condition = models.IntegerField(choices=CONDITIONS)
    notes = models.TextField(blank=True, default='')

    def __str__(self):
        return '{}:{}'.format(self.recorded_at.strftime('%Y-%m-%d %H:%M:%S'), self.get_condition_display())

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms


class LogoutForm(forms.Form):
    pass

users/views.py
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import FormView, CreateView

from . import forms

def dashboard(request):
    return render(request, 'users/dashboard.html')

class LogoutView(LoginRequiredMixin,FormView):
    form_class = forms.LogoutForm
    template_name = 'users/logout.html'

    def form_valid(self, form):
        logout(self.request)
        return HttpResponseRedirect(reverse('home'))


class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('users:dashboard')

templates/index.html
{% extends "layout.html" %}

{% block content %}

<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Feelings</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Feelings{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

      <!-- Latest compiled and minified CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/feelings.css' %}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Feelings</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
                <li><a href="{% url 'users:login' %}">Login</a> </li>
                <li><a href="{% url 'users:signup' %}">Sign up</a></li>
            {% else %}
                    <li><a href="#">Record</a></li>
                    <li><a href="{% url "users:logout" %}">Logout</a></li>
            {%  endif %}
        </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
        <div class="container">
            <hr>

          <footer>
            <p>&copy; 2016 Company, Inc.</p>
          </footer>
        </div> <!-- /container -->



        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="js/bootstrap.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

users/templates/users/dashboard.html
{%  extends "layout.html" %}

{%  block title %}Dashboard | {{ block.super }}{%  endblock %}

{% block content %}
<div class="container">
    <h1>Dashboard</h1>
</div>

{%  endblock %}

users/templates/users/logout.html
{% extends "layout.html" %}

{% block title %} Logout  | {{ block.super }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Logout</h3>
            <form method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Logout" class="btn btn-default">
            </form>
        </div>
            <div class="col-md-6">
                <h3>come back soon</h3>
                <p>This site works best!</p>
            </div>
    </div>
</div>
{% endblock %}

users/templates/users/signup.html
{% extends "layout.html" %}
{% load bootstrap3 %}
{% block title %} Signup | {{ block.super }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Signup</h3>
            <form method="POST">
                {% bootstrap_form form %}
                {% csrf_token %}
                <input type="submit" value="signup" class="btn btn-default">
            </form>
        </div>
            <div class="col-md-6">
                <h3>come back soon</h3>
                <p>This site works best!</p>
            </div>
    </div>
</div>
{% endblock %}